export const mockCustomers = [
  {
    first_name: "Alice",
    last_name: "Tan",
    email: "alice.tan@example.com",
    mobile: "+65 9123 4567",
    resume_link: "https://example.com/resumes/alice.tan.pdf",
    status: "review",
    interview_date: "",
    notes: "",
    id: "1",
  },
  {
    first_name: "Carl",
    last_name: "Ong",
    email: "carl.ong@example.com",
    mobile: "+65 9234 5678",
    resume_link: "https://example.com/resumes/carl.ong.pdf",
    status: "review",
    interview_date: "",
    notes: "Referred by the engineering lead.",
    id: "2",
  },
  {
    first_name: "Hui Min",
    last_name: "Lim",
    email: "huimin.lim@example.com",
    mobile: "+65 8345 6789",
    resume_link: "https://example.com/resumes/huimin.lim.pdf",
    status: "review",
    interview_date: "",
    notes: "",
    id: "3",
  },
  {
    first_name: "Rajesh",
    last_name: "Kumar",
    email: "rajesh.kumar@example.com",
    mobile: "+65 9456 7890",
    resume_link: "https://example.com/resumes/rajesh.kumar.pdf",
    status: "review",
    interview_date: "",
    notes: "Five years of Java. Check notice period.",
    id: "4",
  },
  {
    first_name: "Siti",
    last_name: "Rahman",
    email: "siti.rahman@example.com",
    mobile: "+65 8567 8901",
    resume_link: "https://example.com/resumes/siti.rahman.pdf",
    status: "review",
    interview_date: "",
    notes: "",
    id: "5",
  },
  {
    first_name: "Marcus",
    last_name: "Chua",
    email: "marcus.chua@example.com",
    mobile: "+65 9678 9012",
    resume_link: "https://example.com/resumes/marcus.chua.pdf",
    status: "review",
    interview_date: "",
    notes: "",
    id: "6",
  },
  {
    first_name: "Priya",
    last_name: "Nair",
    email: "priya.nair@example.com",
    mobile: "+65 8789 0123",
    resume_link: "https://example.com/resumes/priya.nair.pdf",
    status: "review",
    interview_date: "",
    notes: "Applied through LinkedIn.",
    id: "7",
  },
  {
    first_name: "Ben",
    last_name: "Lim",
    email: "ben.lim@example.com",
    mobile: "+65 9111 2222",
    resume_link: "https://example.com/resumes/ben.lim.pdf",
    status: "scheduled",
    interview_date: "2026-10-01T10:00",
    notes: "",
    id: "8",
  },
  {
    first_name: "Wei Jie",
    last_name: "Goh",
    email: "weijie.goh@example.com",
    mobile: "+65 8222 3333",
    resume_link: "https://example.com/resumes/weijie.goh.pdf",
    status: "scheduled",
    interview_date: "2026-10-01T14:00",
    notes: "Strong Python. Ask about React.",
    id: "9",
  },
  {
    first_name: "Nurul",
    last_name: "Aisyah",
    email: "nurul.aisyah@example.com",
    mobile: "+65 9333 4444",
    resume_link: "https://example.com/resumes/nurul.aisyah.pdf",
    status: "scheduled",
    interview_date: "2026-10-02T11:00",
    notes: "",
    id: "10",
  },
  {
    first_name: "Kenneth",
    last_name: "Yeo",
    email: "kenneth.yeo@example.com",
    mobile: "+65 8444 5555",
    resume_link: "https://example.com/resumes/kenneth.yeo.pdf",
    status: "scheduled",
    interview_date: "2026-10-03T15:30",
    notes: "",
    id: "11",
  },
  {
    first_name: "Mei Ling",
    last_name: "Wong",
    email: "meiling.wong@example.com",
    mobile: "+65 9555 6666",
    resume_link: "https://example.com/resumes/meiling.wong.pdf",
    status: "scheduled",
    interview_date: "2026-10-05T09:30",
    notes: "Prefers a morning slot.",
    id: "12",
  },
  {
    first_name: "Arjun",
    last_name: "Menon",
    email: "arjun.menon@example.com",
    mobile: "+65 8666 7777",
    resume_link: "https://example.com/resumes/arjun.menon.pdf",
    status: "scheduled",
    interview_date: "2026-10-06T16:00",
    notes: "",
    id: "13",
  },
  {
    first_name: "Dan",
    last_name: "Ng",
    email: "dan.ng@example.com",
    mobile: "+65 9777 8888",
    resume_link: "https://example.com/resumes/dan.ng.pdf",
    status: "offered",
    interview_date: "2026-09-24T14:00",
    notes: "Good system design answers.",
    id: "14",
  },
  {
    first_name: "Jasmine",
    last_name: "Teo",
    email: "jasmine.teo@example.com",
    mobile: "+65 8888 9999",
    resume_link: "https://example.com/resumes/jasmine.teo.pdf",
    status: "shortlisted",
    interview_date: "2026-09-25T10:00",
    notes: "",
    id: "15",
  },
  {
    first_name: "Farid",
    last_name: "Ismail",
    email: "farid.ismail@example.com",
    mobile: "+65 9012 3456",
    resume_link: "https://example.com/resumes/farid.ismail.pdf",
    status: "shortlisted",
    interview_date: "2026-09-25T15:00",
    notes: "Team fit is strong.",
    id: "16",
  },
  {
    first_name: "Chloe",
    last_name: "Sim",
    email: "chloe.sim@example.com",
    mobile: "+65 8123 4560",
    resume_link: "https://example.com/resumes/chloe.sim.pdf",
    status: "shortlisted",
    interview_date: "2026-09-28T11:30",
    notes: "",
    id: "17",
  },
  {
    first_name: "Vikram",
    last_name: "Singh",
    email: "vikram.singh@example.com",
    mobile: "+65 9234 5601",
    resume_link: "https://example.com/resumes/vikram.singh.pdf",
    status: "shortlisted",
    interview_date: "2026-09-29T14:30",
    notes: "",
    id: "18",
  },
  {
    first_name: "Eve",
    last_name: "Koh",
    email: "eve.koh@example.com",
    mobile: "+65 8345 6012",
    resume_link: "https://example.com/resumes/eve.koh.pdf",
    status: "offered",
    interview_date: "2026-09-15T10:00",
    notes: "Offer sent. Waiting for reply.",
    id: "19",
  },
  {
    first_name: "Daryl",
    last_name: "Lee",
    email: "daryl.lee@example.com",
    mobile: "+65 9456 0123",
    resume_link: "https://example.com/resumes/daryl.lee.pdf",
    status: "offered",
    interview_date: "2026-09-16T14:00",
    notes: "",
    id: "20",
  },
  {
    first_name: "Sarah",
    last_name: "Low",
    email: "sarah.low@example.com",
    mobile: "+65 8560 1234",
    resume_link: "https://example.com/resumes/sarah.low.pdf",
    status: "offered",
    interview_date: "2026-09-17T11:00",
    notes: "Asked for a later start date.",
    id: "21",
  },
  {
    first_name: "Hafiz",
    last_name: "Osman",
    email: "hafiz.osman@example.com",
    mobile: "+65 9601 2345",
    resume_link: "https://example.com/resumes/hafiz.osman.pdf",
    status: "offered",
    interview_date: "2026-09-18T16:00",
    notes: "",
    id: "22",
  },
  {
    first_name: "Frank",
    last_name: "Goh",
    email: "frank.goh@example.com",
    mobile: "+65 8012 3450",
    resume_link: "https://example.com/resumes/frank.goh.pdf",
    status: "rejected",
    interview_date: "",
    notes: "Not enough frontend experience.",
    id: "23",
  },
  {
    first_name: "Grace",
    last_name: "Lee",
    email: "grace.lee@example.com",
    mobile: "+65 9123 4501",
    resume_link: "https://example.com/resumes/grace.lee.pdf",
    status: "rejected",
    interview_date: "2026-09-20T10:00",
    notes: "Declined the offer.",
    id: "24",
  },
  {
    first_name: "Terence",
    last_name: "Pang",
    email: "terence.pang@example.com",
    mobile: "+65 8234 5012",
    resume_link: "https://example.com/resumes/terence.pang.pdf",
    status: "rejected",
    interview_date: "",
    notes: "",
    id: "25",
  },
];

// Helper to generate unique IDs
export const generateCustomerId = () => "c" + Date.now();
